# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 坐标转化.py
# Created on: 2018-03-05 02:05:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:

# Process: 创建自定义地理(坐标)变换
#arcpy.CreateCustomGeoTransformation_management("@转换名称","@输入坐标系", "@输出地理坐标系", "@转换方式")

# Process: 投影
try:
    arcpy.Project_management(r"@源数据", r"@投影后数据", "@目标坐标系", "@转换名称", "@源坐标系")
except Exception , err :
    print err.message.decode("utf-8").encode('gb2312')
else:
    print 1
