# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 坐标转化.py
# Created on: 2018-03-05 02:05:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:

# Process: 创建自定义地理(坐标)变换
#arcpy.CreateCustomGeoTransformation_management("bj54to2000","@输入坐标系", "@输出地理坐标系", "@转换方式")

# Process: 投影
try:
    arcpy.Project_management(r"D:\Documents\GitHub\CoordProjectManger\Release\lsdata\180509231156.shp", r"D:\Documents\GitHub\CoordProjectManger\Release\lsdata\180509231221_prj.shp", "GEOGCS['GCS_Beijing_1954',DATUM['D_Beijing_1954',SPHEROID['Krasovsky_1940',6378245.0,298.3]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "bj54to2000", "GEOGCS['GCS_China_Geodetic_Coordinate_System_2000',DATUM['D_China_2000',SPHEROID['CGCS2000',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")
except Exception , err :
    print err.message.decode("utf-8").encode('gb2312')
else:
    print 1
