# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 坐标转化.py
# Created on: 2018-03-05 02:05:46.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:

# Process: 创建自定义地理(坐标)变换
try:
    arcpy.CreateCustomGeoTransformation_management("bj54to2000","GEOGCS['GCS_China_Geodetic_Coordinate_System_2000',DATUM['D_China_2000',SPHEROID['CGCS2000',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "GEOGCS['GCS_Beijing_1954',DATUM['D_Beijing_1954',SPHEROID['Krasovsky_1940',6378245.0,298.3]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "GEOGTRAN[METHOD['Position_Vector'],PARAMETER['X_Axis_Translation',-2.07673185871283],PARAMETER['Y_Axis_Translation',-2.58435416530156],PARAMETER['Z_Axis_Translation',0],PARAMETER['X_Axis_Rotation',0],PARAMETER['Y_Axis_Rotation',0],PARAMETER['Z_Axis_Rotation',-0.0131119510232601],PARAMETER['Scale_Difference',0.0239995380763965]]")
except Exception , err :
    print err.message.decode('utf-8').encode('gb2312')
else:
    print 1
# Process: 投影
#arcpy.Project_management(r"@源数据", r"@投影后数据", "@目标坐标系", "bj54to2000", "@源坐标系")

